### ISSUE TITLE
在安卓6.0以上的机器，使用自动安装的时候报错，报错信息如下：

### ISSUE THREAD

**Issue by liu-miao-miao** [1556173267/react-native-apk-manager#3]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
    at androidx.core.content.FileProvider.b(Unknown Source:21)
    at androidx.core.content.FileProvider.a(Unknown Source:13)
    at androidx.core.content.FileProvider.a(Unknown Source:0)
    at com.superhao.react_native_apk_manager.ApkManagerModule.installApk(Unknown Source:76)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:148)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
    at android.os.Looper.loop(Looper.java:224)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by liu-miao-miao** [comment]
`"react-native-apk-manager": "^1.1.0",`

**Comment by bohehe** [comment]
看报错有可能是没有给安装应用权限造成的，Unknown Source:37、
我这边在安卓7.1以下也有这个问题。

**Comment by bohehe** [comment]
读写权限问题，解决了

**Comment by liu-miao-miao** [comment]
> 读写权限问题，解决了

请问下你是怎么解决的

**Comment by liu-miao-miao** [comment]
> 读写权限问题，解决了

请问下你是怎么解决的

**Comment by liu-miao-miao** [comment]
> 读写权限问题，解决了

请问下你是怎么解决的

**Comment by bohehe** [comment]
> > 读写权限问题，解决了
> 
> 请问下你是怎么解决的

apk包需要读写存储权限才能下载安装，我把下载目录配置到external目录（这个目录安卓所有设备都有，可以放心使用），然后在下载更新apk时，向用户获取读写存储权限，然后就好了。关键问题还是向用户获取读写存储权限

**Comment by bohehe** [comment]
> > 读写权限问题，解决了
> 
> 请问下你是怎么解决的

其ApkManagerModule.java文件的installApk方法要重写一下
```
    @ReactMethod
    public void installApk(String filePath) {
        try {
            File file = new File(filePath);
            String authority = this.getReactApplicationContext().getPackageName() + ".provider";
            Uri fileUri = FileProvider.getUriForFile(this.getReactApplicationContext(), authority, file);
            Intent intent = new Intent(Intent.ACTION_VIEW);

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION | Intent.FLAG_ACTIVITY_NEW_TASK);
                intent.setDataAndType(fileUri, "application/vnd.android.package-archive");
            } else {
                intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                intent.setDataAndType(Uri.fromFile(file), "application/vnd.android.package-archive");
            }
            this.getReactApplicationContext().startActivity(intent);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```
